### ISSUE TITLE
Python: specifying an effect is broken.

### ISSUE THREAD

**Issue by gshpychka** [udondan/iam-floyd#110]
**I'm using the package**

- [ ] iam-floyd
- [x] cdk-iam-floyd

**I'm using the package in language**
- [ ] TypeScript/JavaScript (npm)
- [x] Python (pip)

**Describe the problem**

Works:
`statement.Cloudwatch().to_describe_alarms()`

Does not work:
`statement.Cloudwatch().allow().to_describe_alarms()`

Typing error: `Cannot access member "to_describe_alarms" for type "PolicyStatementWithEffect". Member "to_describe_alarms" is not known`.

Only thing that works with `allow()` is the `to()` method. No service-specific methods work.

I'm using the latest version of `cdk-iam-floyd`.

**Comment by gshpychka** [comment]
@udondan can you take a look?

**Comment by udondan** [comment]
Going to close this. The problem is already tracked in #99.
