### ISSUE TITLE
add forAccounts that accepts iterable

### ISSUE THREAD

**Issue by eli88fine** [udondan/iam-floyd#122]
I've been excited when trying out this package so far, and others within my organization as well.  However, we noticed one pain point at the moment.  We are using a multi-account strategy (separate pipeline, dev, testing, staging, prod), and we have several cases where we need to grant IAM permissions to a list of accounts.

Would it be possible to create a `forAccounts` function (or an overload of the existing `forAccount` function) that accepts an iterable of strings?

I think this is where it would be added, but I'm still trying to understand the library organization.
https://github.com/udondan/iam-floyd/blob/a97fd13b437697ef009addee6350a369834b9a5d/lib/shared/policy-statement/6-principals.ts#L99

**Comment by udondan** [comment]
Hi Eli,

you could just iterate over the list and add the accounts one by one, e.g.

```ts
const foo = new statement.Xxx()...
accounts.forEach((account) =>
   foo.forAccount(account);
);
```

While this works, it's ugly. I agree. :)

Shouldn't be too hard to implement. Will look into it.

Daniel

**Comment by udondan** [comment]
I have implemented the feature in the existing method. (Most of the other `for*` methods now have the same functionality) It now takes any number of account. 

When you have a list available you can pass it like this:

```ts
const accounts = ['1234567890', '0987654321'];
const foo = new statement.Xxx()
  .forAccount(...accounts)
```

```py
accounts = ['1234567890', '0987654321'];
foo = statement.Xxx() \
               .for_account(*accounts)
```

This is going to be in the next automated release. Might be tonight or later this week, depending on when AWS changes something in the docs :)
