### ISSUE TITLE
How to create an array of statements?

### ISSUE THREAD

**Issue by akefirad** [udondan/iam-floyd#159]
I'm not entirely sure if this is a bug or a silly mistake I'm making. I've got a stack in which I create an IAM role with some policy. I wrote some unit tests and everything works just fine. However when I try to `synth` the stack, it fails with
```log
> cdk --app bin/sandbox.js "synth"

/Users/rad/work/cdk-app/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2
  `);throw new Error(`Validation failed with the following errors:
     ^

Error: Validation failed with the following errors:
  [AppsServiceAccountRolesStack/AppServiceAccountPolicy] A PolicyStatement must specify at least one 'action' or 'notAction'.
  [AppsServiceAccountRolesStack/AppServiceAccountPolicy] A PolicyStatement used in an identity-based policy must specify at least one resource.
    at validateTree (/Users/rad/work/cdk-app/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:2:12)
    at Object.synthesize (/Users/rad/work/cdk-app/node_modules/aws-cdk-lib/core/lib/private/synthesis.js:1:598)
    at App.synth (/Users/rad/work/cdk-app/node_modules/aws-cdk-lib/core/lib/stage.js:1:2126)
    at Object.<anonymous> (/Users/rad/work/cdk-app/bin/sandbox.js:48:5)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Subprocess exited with error 1
```
Here's the code snippet (Let me know if I need to provide a sample to reproduce the issue.)
```ts
const newStatements = (
  sysName: string,
  appName: string,
  env: GenericStackEnv,
): Array<iam.PolicyStatement> => {
  const sns1 = new statements.Sns() //
    .allow()
    .toListTopics()
    .on("*");

  const sns2 = new statements.Sns() //
    .allow()
    .toPublish()
    .toGetTopicAttributes()
    .onTopic(`${appName}-*`, env.account, env.region, "aws");

  return [sns1, sns2];
};
```
Interestingly when I create a single statement object and return a singleton list, everything works just fine.
Also if I call `toJSON()` method on any of the statement or on the policy to which the statements are added, everything works just fine too.
The other thing I found out is that if I call `addCondition` on any of the statement, again, everything works just fine.
What am I missing? 😕 
Thanks.

**Comment by udondan** [comment]
What version of Floyd and CDK are you using? I'm quite positive that this is caused by the recent CDK change, which made all versions of Floyd incompatible. See #153.

I released a fix today, so please try again with the latest version.

**Comment by akefirad** [comment]
Ah upgrading both aws-cdk and iam-floyd seems to fix the issue. At least I can't reproduce it. Thanks for the response. Feel free to close the issue.

**Comment by udondan** [comment]
Yep, then I guess you had CDK 2.29.x running before. Unfortunately Floyd cannot be used with that. 

Glad this works now 🙂
