### ISSUE TITLE
Hardcode "aws" as Default Partition?

### ISSUE THREAD

**Issue by akefirad** [udondan/iam-floyd#296]
I'm guessing the majority of users would deploy their infrastructure on AWS partition. So does it make sense to make it the default partition? The challenge is that it's a breaking change.

The benefit is that the generated document becomes much more readable without all `Join`s and `Ref`s.
And if I want to add it manually, since the partition comes at the end in the list of method arguments, I have to put everything including account and region.

What if we provide something like `onAwsFoo` methods?

Happy to help if needed.

**Comment by udondan** [comment]
I think I don't understand the problem.

Are you writing about the .on* methods, e.g. `Sts.onRole()`. In iam-floyd the default partion actually is `aws`, in cdk-iam-floyd the default partion is the partition of the CFN Stack (`Aws.PARTITION` from the CDK lib).

Doesn't this work for you?

**Comment by akefirad** [comment]
Let's say if you want to give permission to execute a lambda, you'd write:
```ts
new stmts.Lambda()
    .onFunction("Foo-Function")
    .onFunction("Bar-Function");
```
Now the above generates:
```json
{
  "Action": "lambda:InvokeFunction",
  "Effect": "Allow",
  "Resource": [
    {
      "Fn::Join": [
        "",
        [
          "arn:",
          {
            "Ref": "AWS::Partition"
          },
          ":lambda:*:*:function:Foo-Function"
        ]
      ]
    },
    {
      "Fn::Join": [
        "",
        [
          "arn:",
          {
            "Ref": "AWS::Partition"
          },
          ":lambda:*:*:function:Bar-Function"
        ]
      ]
    }
  ]
}
```
But if you set the partition, then it'd be like this:
```json
{
  "Action": "lambda:InvokeFunction",
  "Effect": "Allow",
  "Resource": [
    "arn:aws:lambda:*:*:function:Foo-Function",
    "arn:aws:lambda:*:*:function:Bar-Function"
  ]
}
```
Which is much more readable. It also makes diff and review operation a lot easier since the `diff` command shows the actual text diff which is cleaner for the later case.

Now the challenge is that, to get above version, I have to specify not only the partition, but also account and region:
```ts
new stmts.Lambda()
    .onFunction("Foo-Function", "*", "*", "aws")
    .onFunction("Bar-Function", "*", "*", "aws");
```
I'm trying to find a solution for not having to type `, "*", "*", "aws"` part.

As for the method name suggestion (assuming we don't want to have a breaking change), I was thinking if it makes sense to have an overload method like:
```ts
new stmts.Lambda()
    .onAwsFunction("Foo-Function") // equivalent to .onFunction("Foo-Function", "*", "*", "aws")
```

Does that make sense?

**Comment by udondan** [comment]
Ah I see, it's about the generated template, not the outcome when deploying.

I'm not entirely sure it's possible, but I think we could implement a single method to set the default partition, e.g.

```ts
new stmts.Lambda()
    .setDefaultPartition('aws')
    .onFunction("Foo-Function")
    .onFunction("Bar-Function";
```

Or alternatively put it in the constructor

```ts
new stmts.Lambda(undefined, 'aws')
    .onFunction("Foo-Function")
    .onFunction("Bar-Function";
```

(First constructor argument is the sid of the statement)

Or make the first constructor argument optionally an object, so we can extend it later with other statement setting

```ts
new stmts.Lambda({defaultPartition: "aws"})
    .onFunction("Foo-Function")
    .onFunction("Bar-Function";

new stmts.Lambda({sid: "foo"})
    .onFunction("Foo-Function")
    .onFunction("Bar-Function";

new stmts.Lambda({defaultPartition: "aws", sid: "foo"})
    .onFunction("Foo-Function")
    .onFunction("Bar-Function";

new stmts.Lambda("foo") // backwards compatible, when string then it's the sid
    .onFunction("Foo-Function")
    .onFunction("Bar-Function";
```

I think I like the last option best. What do you think?

---

Just for the fun of it, I created a factory that you could use without any changes on the package:

```ts
import * as statement from 'cdk-iam-floyd/lib/generated';

type InstantiableClass = new (...args: any[]) => any;

function awsStatement<T extends keyof typeof statement>(className: T): InstanceType<typeof statement[T]> {
  const Class = class extends (statement[className] as InstantiableClass) {
    constructor() {
      super();
    }
    freeze() {
      if (!this.frozen) {
        this.floydResources = this.floydResources.map((r: any) => {
          return r.replace(/arn:[^:]+:/g, 'arn:aws:');
        });
      }
      console.log(this.floydResources);
      return super.freeze();
    }
  } as InstantiableClass;

  const instance = new Class();
  return instance as InstanceType<typeof statement[T]>;
}

...

awsStatement('Lambda')
  .onFunction("Foo-Function")
  .onFunction("Bar-Function");
```

The freeze method is called by the CDK when its generating the template. In there we can override the arns of all recorded resources.

**Comment by akefirad** [comment]
Right, it's just the generated template. I also like the latter more. Could potentially help with other extensions (for example, default account, or region maybe?). Sounds like a clean solution. The only minor comment is how to make it shorter and more concise? (e.g. `defaultPartition` is a bit too long, considering the value of the feature.) But I guess that just implementation details. You know what I mean?
Another random idea; what is the purpose of `"@aws-cdk/core:target-partitions": ["aws"],` in `cdk.json`? Do you think if we can make use of `cdk.json` for externalizing such configuration? This has the benefit of reusing the same code for different partition yet having cleaner templates. Not a huge win, but still.

**Comment by akefirad** [comment]
On that note, a quick question: why the output when account and region are missing is `*`. Is that enforced by CDK or is it your decision?

**Comment by akefirad** [comment]
Hm, the in* methods idea is neat, but considering the fact that the majority of cases will be the account/region of the stack, I'm not sure it'll be enough. I think your second point is more interesting:
>The defauls are in floyd code. I would actualy like to change that to the account/region of the stack. But that certainly is a breaking change, most people would't catch in their renovate/dependabot/... automation. I know I wouldn't. :)

And agree with the point that people probably won't notice it (tho I personally check 😁). Not sure what to do. On one hand the lib is not GA yet, so theoretically breaking changes are allowed. On the other hand it's a nasty change.

Did you notice the new (don't remember since when) feature of CDK which give warning about important changes? Maybe you can use the same feature? (random idea: print a warning asking people to set the account and region explicitly if they want them to be `*`, with a heads up that on release v1.0 the default behavior would be "in stack account/region").

**Comment by udondan** [comment]
Technically you're right... Though I would like to avoid to break all apps. But I have an idea. For other features I have planned, I need to change the exports of the package. I will do this at the same time. Then the app will fail to build and all users need to update their imports and hopefully will see the ARN change in the changelog.
