### ISSUE TITLE
Trust policies

### ISSUE THREAD

**Issue by cmclaughlin** [udondan/iam-floyd#31]
Is it possible to generate this?

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "rds.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```

Just getting started and everything I've generated has a `Resource` key/value.
If it's not possible, could we consider this a feature request?

**Comment by udondan** [comment]
Hi and thanks for the issue. You're correct, currently it always adds all resources. I somehow missed that.

I had prepared a change this morning to fix this, but then got distracted with my day job and now I'm afk... Will test and push tomorrow.

Thanks again,
Daniel

**Comment by cmclaughlin** [comment]
Sounds good! Thanks for the awesome library.

**Comment by udondan** [comment]
Alright it started raining so I came back earlier than expected...

Release 0.70.1 has been released, which no longer automatically add the `Resource` key if the statement has a principal.

I assume you're using the iam-floyd package without CDK, right? Where I got stuck this morning was to test the CDK variant and it turns out you actually cannot add a `PolicyStatement` to a role because it expects an `IPrincipal`.

In the version without CDK you can create the trust policy now like this:

```typescript
new statement.Sts()
  .allow()
  .toAssumeRole()
  .forService('rds.amazonaws.com')
```

Which will produce this:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "sts:AssumeRole"
      ],
      "Principal": {
        "Service": [
          "rds.amazonaws.com"
        ]
      }
    }
  ]
}
```

In CDK-land you can do the same if you simply wanted the statement as JSON. But if you wanted to add it to a role you would do it like this instead:

```typescript
new iam.Role(this, 'Role', {
  roleName: 'test-role',
  description: 'Test Role',
  assumedBy: new iam.ServicePrincipal('rds.amazonaws.com),
  managedPolicies: [...],
});
```

Let me know if my assumption was wrong and you need it somehow in CDK.

Cheers,
Daniel

**Comment by cmclaughlin** [comment]
Thanks!

I'm using the Python library with CDK for Terraform. So basically just raw Python.

I can confirm it works:

```python
>>> import iam_floyd as statement
>>> statement.Sts().allow().to_assume_role().for_service('rds.amazonaws.com').to_json()
{'Action': ['sts:AssumeRole'], 'Principal': {'Service': ['rds.amazonaws.com']}}
```

**Comment by udondan** [comment]
Thanks for confirming. I myself only use it in TypeScript with AWS CDK. Always good to hear it's working in other combinations!

**Comment by cmclaughlin** [comment]
@udondan just getting around to using it... perhaps I'm still just not familar with the library, but I think we need a "Effect": "Allow" key/value pair.  

The particular policy I'm trying to model is documented here:

https://docs.aws.amazon.com/neptune/latest/userguide/bulk-load-tutorial-IAM.html

**Comment by cmclaughlin** [comment]
Ok, that's probably more of a usage question... my S3 policy is the Effect KV also. Please let me know if have any hints!

**Comment by udondan** [comment]
Hi Charles, the Effect in a policy statement is optional and defaults to `Allow`, that's why it's not explicitly set. 

The methods to set the Effect are `allow()` and `deny()`.

**Comment by cmclaughlin** [comment]
Maybe it's optional for normal policy statements, but not trust relationships?

<img width="780" alt="Screen Shot 2020-10-05 at 3 02 02 PM" src="https://user-images.githubusercontent.com/1061109/95136892-d68cdf80-071b-11eb-8440-ea14fcbca09b.png">

**Comment by udondan** [comment]
Ah, interesting. Never knew that. Thanks!

I really need to add a lot more tests, not only creating statements but actually creating policies to catch these things.

**Comment by udondan** [comment]
Version 0.76.1 will be released in a minute which includes a fix for this. Thanks again for bringing this to my attention!
