### ISSUE TITLE
Why Instantiate Condition Operator?

### ISSUE THREAD

**Issue by akefirad** [udondan/iam-floyd#328]
Let's say I need to have a `StringEquals` condition. Why do I need to instantiate an instance of `Operator` like this: `new statements.Operator().stringEquals()`? Or is there a better way to do it?

**Comment by udondan** [comment]
It's a class for more complex situations, where operator can get modifiers. For example:

`new statements.Operator().stringEquals().forAnyValue().ifExists()` would generate: `ForAnyValue:StringEqualsIfExists`

You don't have to use this class, you can also just pass a string or have your own helper, e.g. a simple enum with the operators you need.

I considered enums as well, but all available operators with potentially 1 or 2 of 3 possible modifiers would permunate into a quite long list.

**Comment by akefirad** [comment]
I see. Do you think if it makes sense to provide something like `Operator.stringEquals()`?

**Comment by udondan** [comment]
You mean adding a static method on the class? It would make sense but unfortunately it's not possible. JSII doesn't allow it. It would of course perfectly work for TS but JSII has to limit the functionality to what's supported by all the languages supported by JSII. Here is what hapens when trying to add it:

```
error JSII5013: Member "stringEquals" of class "iam-floyd.Operator" has both a static and an instance delcaration
```

**Comment by akefirad** [comment]
Ah I see. Ok I guess we have leave it at that. Thanks.
