### ISSUE TITLE
Remove jsii and python support

### ISSUE THREAD

**Issue by udondan** [udondan/iam-floyd#397]
jsii has been such a pain in the ass over the years and I am no longer willing to deal with it. I have no capacity to permantly fix compatiblitity issues.

![tenor-111401315](https://user-images.githubusercontent.com/6443408/233839710-02001e17-495b-44ad-be0b-4cb18802f4bf.gif)

Also, jsii is the single [blocker](https://github.com/aws/jsii/issues/2773) for implementing new features in this library. 

Python support will be dropped so we no longer have a need for this jsii.

**Comment by vincenthsh** [comment]
Oh lol, I was just looking to add JSII support, I'm trying to write a jsii CDKTF construct which expose `PolicyStatement` building from `iam-floyd` and jsii complains when I bundle.. I'm quite confused and I was about to give up by publishing iam-floyd with the `.jsii` manifest so I can just keep at as a peer dependency.

Is there any way to do this without re-adding JSII? Perhaps it's necessary to do something similar to how the `AWS CDK` package is built?
