### ISSUE TITLE
`Batch.onJobDefinition` Generates a `JobDefinitionRevsion` Resource

### ISSUE THREAD

**Issue by akefirad** [udondan/iam-floyd#431]
```ts
              new statement.Batch()
                .allow()
                .toSubmitJob()
                .onJobDefinition("my-job-def", "some-revision"),
            ],
```
For job definition ARNs, there's no revision, according to the [docs](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsbatch.html).
Let me know if I can help with anything.

**Comment by akefirad** [comment]
Hm it's weird, it doesn't work without giving the revision ARN, i.e. it's not a job-definition-arn, it's a job-definition-revision-arn. The doc seems to be wrong?

**Comment by akefirad** [comment]
Anyway, the method is not ideal atm. Either we have to have two different methods or make the revision optional in this method.

**Comment by udondan** [comment]
This should be solved. The project was not updated for some time since it required a lot of work gettng it running again. With version 601.1 there now have been lots of updates from the docs, incuding the changes in batch. Thre now is onJobDefinition and onJobDefinitionRevision.
