### ISSUE TITLE
"Could not find a declaration file" error when compiling with version 0.601.1

### ISSUE THREAD

**Issue by l0b0** [udondan/iam-floyd#450]
I have a Dependabot PR to "bump cdk-iam-floyd from 0.507.0 to 0.601.1" in a private project. When running `tsc` in this PR there's a new error:

```console
> tsc

foo.ts:4:20 - error TS7016: Could not find a declaration file for module 'cdk-iam-floyd'. '…/node_modules/cdk-iam-floyd/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/cdk-iam-floyd` if it exists or add a new declaration (.d.ts) file containing `declare module 'cdk-iam-floyd';`

4 import { S3 } from 'cdk-iam-floyd';
                     ~~~~~~~~~~~~~~~
```

The @types/cdk-iam-floyd package does not exist, and I'm reluctant to go down a rabbit hole with creating a .d.ts file without knowing what the actual issue is, or whether this is a bug in the package. What should I do?

**Comment by udondan** [comment]
Thanks @l0b0, I'm on it. I was cleaning up the .npmignore yesterday and now have learned, the rule order actually matters. Will release a fix soon.
