### ISSUE TITLE
`.ifAwsMultiFactorAuthPresent(false)` generates condition with a boolean value

### ISSUE THREAD

**Issue by akefirad** [udondan/iam-floyd#49]
**I'm using the package**
- [ ] iam-floyd: 
- [x] cdk-iam-floyd (v0.106.0)

**I'm using the package in language**
- [x] TypeScript/JavaScript (npm)
- [ ] Python (pip)
- [ ] .Net (NuGet)
- [ ] Java (GitHub packages)

**Describe the problem**
The `ifAwsMultiFactorAuthPresent(false)` call generates the condition `"aws:MultiFactorAuthPresent": false` instead of `"aws:MultiFactorAuthPresent": "false"`. Interestingly when I deploy the policy, on AWS IAM it's `"false"`, (as well as the generated JSON file in `cdk.out` directory), however `synth` command generates the entry with a value of type boolean.

**Comment by akefirad** [comment]
As far as I can tell, both styles work. However everywhere, the value used is of type string (`"true"` or `"false"`). I'd suggest to convert the boolean value to string just to be consistent. Let me know if you need the PR.

**Comment by udondan** [comment]
Thanks for creating the issue. I agree, both styles work but consistency is king. :muscle: I'll release a new version shortly which will take care of the conversion.

**Comment by udondan** [comment]
The change is released in version [v0.108.0](https://github.com/udondan/iam-floyd/releases/tag/v0.108.0).
