### ISSUE TITLE
Delete stacks collection

### ISSUE THREAD

**Issue by skyrpex** [udondan/iam-floyd#54]
Hi there! This is an awesome project, thank you very much.

I'm trying to build a policy that allows deleting stacks, but am having trouble. It would be nice to create a collection, like the [allowEc2InstanceDeleteByOwner collection](https://github.com/udondan/iam-floyd/blob/9527692bcf64f4f732e6a8cc5934f5f2eedf5f5d/lib/collection/allowEc2InstanceDeleteByOwner.ts#L9).

Does anybody have experience in building such a policy? There are some AWS docs [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/automation-action-deletestack.html) mentioning the IAM Automation assume role, but I'm a bit lost :thinking:

**Comment by udondan** [comment]
Hi Christian,

do you mean just a general policy that allows stack deletion or really like in the  EC2 collection, that only allows stack deletion for stacks the same user has created?

Cheers,
Daniel

**Comment by skyrpex** [comment]
Sorry to bother you, I got really confused but now have a clearer picture. So, I was using this `new statement.Cloudformation().allow().toDeleteStack(),` but the stack deletion was failing anyway. That's because deleting a stack involves many other things, like providing a role ARN suitable for deleting all the contents in the stack.

A collection is not what I need.

**Comment by udondan** [comment]
Glad you found a solution. 😸
