### ISSUE TITLE
How to add AWS:SourceOwner condition

### ISSUE THREAD

**Issue by akefirad** [udondan/iam-floyd#56]
Is there a way to add below without dealing with all the strings?
```
policy.addConditions({ 'StringEquals': { 'AWS:SourceOwner': props.env.account } });
```
I saw there's an issue about conditions, not sure if it's related. Let me know how I can help if needed.

**Comment by udondan** [comment]
This seems to be a simple case of undocumented functionality. 😸 Floyd is fully based on the IAM service documentation and the condition context key is neither mentioned in the [SES docs](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonses.html#amazonses-policy-keys) (I assume this is for SES, right?) nor in the [list of global condition context keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html).
 
I wasn't able to find much about `AWS:SourceOwner`, it only appears in context of SES, so I assume it might actually not be a global condition key but only related to SES. Maybe you know more about it? Either way, if it's global or not, AWS should document it in one or both locations.

Maybe you can suggest the AWS folks to cover this. AWS recently has removed the IAM docs from their public repo, so, the only way left to get this fixed is to contact the related team. They have a link at the bottom of every page in the documentation for this. When it shows up on the IAM SES page it will automatically show up in Floyd as well.

cc: @bonniekeller (manages the [AWS IAM userguide repo](https://github.com/awsdocs/iam-user-guide))

Cheers,
Daniel

**Comment by akefirad** [comment]
I see. You're right it's not listed anywhere. I found it while configuring a SNS topic [here](https://docs.aws.amazon.com/sns/latest/dg/sns-access-policy-use-cases.html#source-account-versus-source-owner).

**Comment by akefirad** [comment]
But generally my question was, what's the plan to support conditions? Is #6 about this question? (let me know if you need a hand.)

**Comment by udondan** [comment]
Documented conditions are available as [if* methods](https://iam-floyd.readthedocs.io/en/v0.130.0/vocabulary.html#if-condition). In case of SES, you can use these methods:

```typescript
.ifFeedbackAddress(...)
.ifFromAddress(...)
.ifFromDisplayName(...)
.ifRecipients(...)
```

Global condition context keys are prefixed with `ifAws` and available on all IAM services. So if `AWS:SourceOwner` would have been documented, it would be available as `.ifAwsSourceOwner(...)`.

#6 is about the _default_ condition operator. (every `if*` method takes an optional operator as last parameter) In my opinion, many types are not documented correctly in the AWS docs. The example mentioned in #6 is `s3:object-lock-remaining-retention-days`. If you look it up in the [documentation](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazons3.html#amazons3-s3_object-lock-remaining-retention-days), you see it is of type `string`. Apparently a numeric type would be a better choice for a number. I found many more of these cases, where types could/should probably be of type Date, ARN or what not. But to find, test and report all these cases to AWS takes time and I haven't been too motivated spend so much time to fix the AWS' docs. I probably will just close the #6 at some point.

Cheers,
Daniel

**Comment by bonniekeller** [comment]
Hello, I saw the mention so I wanted to reach out. Amazon Simple Notification Service is the only service that supports aws:SourceOwner<https://docs.aws.amazon.com/sns/latest/dg/sns-access-policy-use-cases.html#sns-allow-any-aws-resource-to-publish-to-topic>. This key does not work with other services because it is not a global condition key. This key serves the same purpose as aws:SourceAccount<https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourceaccount> which is used to specify the account that owns a resource.

Best Regards,
Bonnie

**Comment by udondan** [comment]
Thanks for clarifying @bonniekeller! 🖖🏼

**Comment by akefirad** [comment]
I'm not sure about the conclusion of this conversation. Feel free to close the ticket if it's not gonna be implemented.

**Comment by udondan** [comment]
Yeah let's close this. I reported the missing condition to the team via the feedback link on the IAM page. Maybe you can do the same. The more reports the better. :)
