### ISSUE TITLE
Migration to AWS CDK 2

### ISSUE THREAD

**Issue by marcodvla** [udondan/iam-floyd#70]
I know it's early days, but any chance of an upgrade to AWS CDK 2.

**Comment by udondan** [comment]
Hi there,

I haven't planned to release a compatible package ahead of the first CDK 2 release. It appears to be quite some effort in regards of automation and release process for npm, pypi, nuget and maven. I don't even know if all these would support release candidates or if I would have to create separate package repos... Currently I don't even have the time to research this.

When the first CDK 2 release is published, I'll immediately take care of releasing a compatible package. From there on, there won't be any compatible releases for CDK 1.x though.

Daniel

**Comment by covolution** [comment]
I believe the core CDK team will be providing compatible releases for both CDK 1.x and CDK2 from the same code base.  No idea how they are doing that trickery or what's involved in term of automation/releases.

We're trialling CDK 2 at the moment so I suppose we will have to remove iam-floyd for now.  That's a real shame because I really like it.

**Comment by udondan** [comment]
Are you all using node? I will have a look at manually releasing an RC for CDK 2. That's hopefully not too complicated.

**Comment by udondan** [comment]
I have manually published v2 compatible packages fore nodejs and Python. Please use these versions:

npm: 0.207.1-pre.0
pypi: 0.207.1.dev0

There won't be regular updates or any automatic publishing until the final release of cdk v2.

**Comment by covolution** [comment]
Thanks very much. Will try the npm modules.

**Comment by udondan** [comment]
v0.300.0 has now been released which is (only) compatible with CDK v2. No further packages compatible to v1. Last v1-comptible version is 0.285.0.
